stages:
  - build
  - dev

variables:
  REGISTRY: "registry.gitlab.com/fucksocietyall/exchange_board"

before_script:
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_USER
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

exchange_board_build:
  stage: build
  tags: 
    - dev
  only:
    - develop
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/exchange_board:$CI_COMMIT_SHA" -f ./Exchange_Board/_docker/gitlab/app/Dockerfile .
    - docker push "$REGISTRY/dev/exchange_board:$CI_COMMIT_SHA"

node_tron_build:
  stage: build
  tags: 
    - dev
  only:
    - develop
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/nodetron:$CI_COMMIT_SHA" -f ./NodeTRON/_docker/app/Dockerfile .
    - docker push "$REGISTRY/dev/nodetron:$CI_COMMIT_SHA"

dev_deploy:
  stage: dev
  # when: manual
  tags:
    - dev
  only:
    - develop
  script:
    - export CONTAINER_PREFIX=project
    - docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker volume rm $(docker volume ls | grep ${CONTAINER_PREFIX}_ | awk '{print $2}') || true
    - docker-compose -p $CONTAINER_PREFIX -f docker-compose.yml up -d
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board composer install
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board php artisan down
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board php artisan config:cache
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board php artisan cache:clear
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board php artisan migrate
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board npm install
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board npm run build
    - docker exec ${CONTAINER_PREFIX}_Exchange_Board php artisan up
    - docker exec ${CONTAINER_PREFIX}_NodeTRON npm install
 