version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./Exchange_Board:/var/www/Exchange_Board
      - ./Exchange_Board/_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./NodeTRON:/var/www/NodeTRON
    ports:
      - 56735:80
    depends_on:
      - exchange_board
      - nodetron
    container_name: ${CONTAINER_PREFIX}_nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"

  exchange_board:
    image: $REGISTRY/dev/exchange_board:$CI_COMMIT_SHA
    volumes:
      - ./Exchange_Board:/var/www/Exchange_Board
      - /var/www/Exchange_Board/vendor
    environment:
      - APP_KEY=$APP_KEY
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_URL=$APP_URL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_DEBUG=$APP_DEBUG
      - WALLET=$WALLET
      - PRIVATE_KEY_WALLET=$PRIVATE_KEY_WALLET  
      - TRON_HOST=$TRON_HOST  
      - QUEUE_CONNECTION=$QUEUE_CONNECTION  
      - BROADCAST_DRIVER=$BROADCAST_DRIVER  
      - PUSHER_APP_ID=$PUSHER_APP_ID  
      - PUSHER_APP_KEY=$PUSHER_APP_KEY  
      - PUSHER_APP_SECRET=$PUSHER_APP_SECRET  
      - PUSHER_PORT=$PUSHER_PORT  
      - PUSHER_SCHEME=$PUSHER_SCHEME  
      - PUSHER_APP_CLUSTER=$PUSHER_APP_CLUSTER  
      - PUSHER_HOST=$PUSHER_HOST  
      - VITE_APP_NAME=$VITE_APP_NAME  
      - VITE_PUSHER_APP_KEY=$VITE_PUSHER_APP_KEY  
      - VITE_PUSHER_HOST=$VITE_PUSHER_HOST  
      - VITE_PUSHER_PORT=$VITE_PUSHER_PORT  
      - VITE_PUSHER_SCHEME=$VITE_PUSHER_SCHEME  
      - VITE_PUSHER_APP_CLUSTER=$VITE_PUSHER_APP_CLUSTER  
    
    ports:
      - "9119:9119"
    command: supervisord
    container_name: ${CONTAINER_PREFIX}_Exchange_Board
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodetron:
    image: $REGISTRY/dev/nodetron:$CI_COMMIT_SHA
    volumes:
      - ./NodeTRON:/var/www/NodeTRON
    ports:
      - 3000:3000
    
    container_name: ${CONTAINER_PREFIX}_NodeTRON
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: ExchangeBoard
  #     MYSQL_ROOT_PASSWORD: root
  #     TZ: Europe/Podgorica
  #   ports:
  #     - 3306:3306 
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --default-time-zone=Europe/Podgorica 
  #   container_name: ${CONTAINER_PREFIX}_mysql

volumes:
  mysql_data: