version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./Exchange_Board:/var/www/Exchange_Board
      - ./Exchange_Board/_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./NodeTRON:/var/www/NodeTRON
    ports:
      - 56735:80
    depends_on:
      - exchange_board
      - nodetron
    container_name: ${CONTAINER_PREFIX}_nginx

  exchange_board:
    image: $REGISTRY/dev/exchange_board:$CI_COMMIT_SHA
    volumes:
      - ./Exchange_Board:/var/www/Exchange_Board
    environment:
      - APP_KEY=$APP_KEY
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_URL=$APP_URL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_DEBUG=$APP_DEBUG
      - WALLET=$WALLET
      - PRIVATE_KEY_WALLET=$PRIVATE_KEY_WALLET  
      - TRON_HOST=$TRON_HOST  
    depends_on:
      - db
    container_name: ${CONTAINER_PREFIX}_Exchange_Board
  nodetron:
    image: $REGISTRY/dev/nodetron:$CI_COMMIT_SHA
    volumes:
      - ./NodeTRON:/var/www/NodeTRON
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: ${CONTAINER_PREFIX}_NodeTRON
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ExchangeBoard
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 
    container_name: ${CONTAINER_PREFIX}_mysql